salt: work
domain: localhost:8090/
server:
  port: 8090
  name: workservice
application: 
     name: ${server.name}
     port: ${server.port}
     domain: ${domain}
spring: 
   cloud: 
      consul:
         host: 127.0.0.1
         port: 8500
         discovery:
           register: true
           hostname: 127.0.0.1
           serviceName: myservice
           healthCheckPath: /api/check
           healthCheckInterval: 15s
           instanceId: workservice
         tags: 
          - 服务提供者
          - 测试服务-
   devtools: 
        restart:
              enabled: true
              additional-paths: src/main/java 
              spring.devtools.restart.exclude: WEB-INF/**
   view: 
        prefix: /templates/
        suffix: ./ftl
   datasource: 
        type: com.alibaba.druid.pool.DruidDataSource 
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/hrmapp?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        passsword: 123456
        dbcp2: 
          initialSize: 5
          minIdle: 5
          maxActive: 20
          max-wait-millis: 6000
        filters: stat,wall,log4j
   EXCHANGE_NAME: ex_log
mybatis: 
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: work.entity.po
 
        