package work.reposisty;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import work.entity.po.User;
@Mapper
public interface UserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Thu Nov 22 16:18:47 CST 2018
	 */
	int deleteByPrimaryKey(String userid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Thu Nov 22 16:18:47 CST 2018
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Thu Nov 22 16:18:47 CST 2018
	 */
	User selectByPrimaryKey(String userid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Thu Nov 22 16:18:47 CST 2018
	 */
	List<User> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Thu Nov 22 16:18:47 CST 2018
	 */
	int updateByPrimaryKey(User record);
}